/* graxml.java */
/* Generated By:JavaCC: Do not edit this line. graxml.java */
package gramatica_xml;
import pr1compilarodores2.Nodo;
import java.io.*;
import java.util.*;

public class graxml implements graxmlConstants {
    public static int contador = 1;
    public static void main( String[] args )throws ParseException
        {
                System.out.println("analisis correcto");
        }

//*********************************************************************************************Inicio
  final public 
Nodo inicio(Nodo raiz) throws ParseException {
    raiz = interno(raiz);
{if ("" != null) return raiz;}
    jj_consume_token(0);
    throw new Error("Missing return statement in function");
  }

  final public Nodo interno(Nodo raiz) throws ParseException {Nodo nodo1;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case tgmi:{
      raiz = tabmaestro(raiz);
{if ("" != null) return raiz;}
      break;
      }
    case Registroi:{
      registro();
      break;
      }
    case Artablai:{
      archivotabla();
      break;
      }
    case Arobji:{
      archivoobj();
      break;
      }
    case Arusui:{
      raiz = arusu(raiz);
{if ("" != null) return raiz;}
      break;
      }
    default:
      jj_la1[0] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

//******************************************************************************************ARCHIVO MAESTRO
  final public 
Nodo tabmaestro(Nodo raiz) throws ParseException {
    jj_consume_token(tgmi);
Nodo tmp = new Nodo("Maestro");
                tmp.setNumNodo(graxml.contador++);
                raiz = tmp;
    raiz = maestro(raiz);
    jj_consume_token(tgmf);
{if ("" != null) return raiz;}
    throw new Error("Missing return statement in function");
  }

//<Dbi> Manombre() <Dbf> Masig()
  final public Nodo maestro(Nodo raiz) throws ParseException {Nodo nodo1;
    jj_consume_token(Dbi);
    raiz = Manombre(raiz);
    jj_consume_token(Dbf);
    raiz = Masig(raiz);
{if ("" != null) return raiz;}
    throw new Error("Missing return statement in function");
  }

  final public Nodo Manombre(Nodo raiz) throws ParseException {Token t1;
    Nodo nodo1;
    jj_consume_token(Nombrei);
    t1 = jj_consume_token(Id);
Nodo tmp = new Nodo(t1.image);
                        tmp.setNumNodo(graxml.contador++);
                        tmp.setColumna(t1.beginColumn);
                        tmp.setFila(t1.beginLine);
                        tmp.setValor("0");
                        nodo1 = tmp;
    jj_consume_token(Nombref);
    nodo1 = Maruta(nodo1);
raiz.addHijo(nodo1);
                                    {if ("" != null) return raiz;}
    throw new Error("Missing return statement in function");
  }

  final public Nodo Maruta(Nodo hermano) throws ParseException {Token t1;
    jj_consume_token(Pathi);
    t1 = jj_consume_token(Ruta);
hermano.setValor(t1.image);
    jj_consume_token(Pathf);
{if ("" != null) return hermano;}
    throw new Error("Missing return statement in function");
  }

  final public Nodo Masig(Nodo raiz) throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case Dbi:{
      raiz = maestro(raiz);
{if ("" != null) return raiz;}
      break;
      }
    default:
      jj_la1[1] = jj_gen;
{if ("" != null) return raiz;}
    }
    throw new Error("Missing return statement in function");
  }

//*********************Archivo registro
  final public 
void registro() throws ParseException {
    jj_consume_token(Registroi);
    recontenido();
    jj_consume_token(Registrof);
  }

  final public void recontenido() throws ParseException {Nodo nodo1;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case Procedurei:{
      jj_consume_token(Procedurei);
      nodo1 = Maruta(null);
      jj_consume_token(Proceduref);
      recontenido();
      break;
      }
    case Objecti:{
      jj_consume_token(Objecti);
      nodo1 = Maruta(null);
      jj_consume_token(Objectf);
      recontenido();
      break;
      }
    case Tablai:{
      jj_consume_token(Tablai);
      tabla();
      jj_consume_token(Tablaf);
      recontenido();
      break;
      }
    default:
      jj_la1[2] = jj_gen;
{if ("" != null) return;}
    }
  }

  final public void tabla() throws ParseException {
    jj_consume_token(Nombrei);
    jj_consume_token(Id);
    jj_consume_token(Nombref);
    jj_consume_token(Pathi);
    jj_consume_token(Ruta);
    jj_consume_token(Pathf);
    jj_consume_token(Rowsi);
    tbcont();
    jj_consume_token(Rowsf);
  }

  final public void tbcont() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case Inti:{
      jj_consume_token(Inti);
      jj_consume_token(Id);
      jj_consume_token(Intf);
      complemento();
      tbcont();
      break;
      }
    case Texti:{
      jj_consume_token(Texti);
      jj_consume_token(Id);
      jj_consume_token(Textf);
      complemento();
      tbcont();
      break;
      }
    case Doublei:{
      jj_consume_token(Doublei);
      jj_consume_token(Id);
      jj_consume_token(Doublef);
      complemento();
      tbcont();
      break;
      }
    case Booli:{
      jj_consume_token(Booli);
      jj_consume_token(Id);
      jj_consume_token(Boolf);
      complemento();
      tbcont();
      break;
      }
    case Datei:{
      jj_consume_token(Datei);
      jj_consume_token(Id);
      jj_consume_token(Datef);
      complemento();
      tbcont();
      break;
      }
    case Dateti:{
      jj_consume_token(Dateti);
      jj_consume_token(Id);
      jj_consume_token(Datetf);
      complemento();
      tbcont();
      break;
      }
    case Obji:{
      jj_consume_token(Obji);
      jj_consume_token(Id);
      jj_consume_token(Objf);
      break;
      }
    default:
      jj_la1[3] = jj_gen;
{if ("" != null) return;}
    }
  }

  final public void complemento() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case Pk:{
      jj_consume_token(Pk);
      complemento();
      break;
      }
    case Fki:{
      jj_consume_token(Fki);
      jj_consume_token(Id);
      jj_consume_token(Fkf);
      complemento();
      break;
      }
    case Nulo:{
      jj_consume_token(Nulo);
      complemento();
      break;
      }
    case Nnulo:{
      jj_consume_token(Nnulo);
      complemento();
      break;
      }
    case Auto:{
      jj_consume_token(Auto);
      complemento();
      break;
      }
    case Unico:{
      jj_consume_token(Unico);
      complemento();
      break;
      }
    default:
      jj_la1[4] = jj_gen;
{if ("" != null) return;}
    }
  }

//**************************************************************************************** ARCHIVO TABLA
  final public 
void archivotabla() throws ParseException {
    jj_consume_token(Artablai);
    conttabla();
    jj_consume_token(Artablaf);
  }

  final public void conttabla() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case Rowi:{
      jj_consume_token(Rowi);
      contcolumna();
      jj_consume_token(Rowf);
      conttabla();
      break;
      }
    default:
      jj_la1[5] = jj_gen;
{if ("" != null) return;}
    }
  }

  final public void contcolumna() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case Ai:{
      jj_consume_token(Ai);
      jj_consume_token(Id);
      jj_consume_token(Af);
      tipo();
      jj_consume_token(Ai);
      jj_consume_token(D);
      jj_consume_token(Id);
      jj_consume_token(Af);
      contcolumna();
      break;
      }
    case Obji:{
      jj_consume_token(Obji);
      jj_consume_token(Id);
      contcolumna();
      jj_consume_token(Objf);
      contcolumna();
      break;
      }
    default:
      jj_la1[6] = jj_gen;
{if ("" != null) return;}
    }
  }

  final public void tipo() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case Id:{
      jj_consume_token(Id);
      break;
      }
    case Num:{
      jj_consume_token(Num);
      break;
      }
    case Texto:{
      jj_consume_token(Texto);
      break;
      }
    case Date:{
      jj_consume_token(Date);
      break;
      }
    case Datetime:{
      jj_consume_token(Datetime);
      break;
      }
    default:
      jj_la1[7] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

//***************************************************************************************ARCHIVO OBJETO
  final public 
void archivoobj() throws ParseException {
    jj_consume_token(Arobji);
    obrows();
    jj_consume_token(Arobjf);
  }

  final public void obrows() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case Obji:{
      jj_consume_token(Obji);
      objcont();
      jj_consume_token(Objf);
      obrows();
      break;
      }
    default:
      jj_la1[8] = jj_gen;
{if ("" != null) return;}
    }
  }

  final public void objcont() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case Nombrei:{
      jj_consume_token(Nombrei);
      jj_consume_token(Id);
      jj_consume_token(Nombref);
      jj_consume_token(Attri);
      tbcont();
      jj_consume_token(Attrf);
      objcont();
      break;
      }
    default:
      jj_la1[9] = jj_gen;
{if ("" != null) return;}
    }
  }

//*************************************************************************************** Archivo Usuarios
  final public 
Nodo arusu(Nodo raiz) throws ParseException {Nodo nodo1;
    jj_consume_token(Arusui);
Nodo tmp = new Nodo("Archivo");
                tmp.setNumNodo(graxml.contador++);
                raiz = tmp;
    raiz = usucon(raiz);
    jj_consume_token(Arusuf);
{if ("" != null) return raiz;}
    throw new Error("Missing return statement in function");
  }

  final public Nodo usucon(Nodo raiz) throws ParseException {Nodo nodo1;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case Usui:{
      jj_consume_token(Usui);
Nodo tmp = new Nodo("Usuario");
                tmp.setNumNodo(graxml.contador++);
                nodo1 = tmp;
      nodo1 = datousu(nodo1);
      jj_consume_token(Usuf);
raiz.addHijo(nodo1);
      raiz = usucon(raiz);
{if ("" != null) return raiz;}
      break;
      }
    default:
      jj_la1[10] = jj_gen;
{if ("" != null) return raiz;}
    }
    throw new Error("Missing return statement in function");
  }

  final public Nodo datousu(Nodo hijo) throws ParseException {Nodo nodo1;
    Token t1;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case Nombrei:{
      jj_consume_token(Nombrei);
      t1 = jj_consume_token(Id);
      jj_consume_token(Nombref);
Nodo tmp = new Nodo(t1.image);
                                    tmp.setNumNodo(graxml.contador++);
                                    tmp.setValor("0");
                                    hijo.addHijo(tmp);
      hijo = datousu(hijo);
{if ("" != null) return hijo;}
      break;
      }
    case Contai:{
      jj_consume_token(Contai);
      t1 = jj_consume_token(Id);
      jj_consume_token(Contaf);
Nodo tmp = new Nodo(t1.image);
                                    tmp.setNumNodo(graxml.contador++);
                                    hijo.addHijo(tmp);
                                    tmp.setValor("0");
      hijo = datousu(hijo);
{if ("" != null) return hijo;}
      break;
      }
    case Noperi:{
      jj_consume_token(Noperi);
Nodo tmp = new Nodo("Nopermiso");
                 tmp.setNumNodo(graxml.contador++);
                 tmp.setValor("0");
                 nodo1 = tmp;
      nodo1 = noper(nodo1);
      jj_consume_token(Noperf);
hijo.addHijo(nodo1);
      hijo = datousu(hijo);
{if ("" != null) return hijo;}
      break;
      }
    case Permisoi:{
      jj_consume_token(Permisoi);
Nodo tmp = new Nodo("Permiso");
                   tmp.setNumNodo(graxml.contador++);
                   tmp.setValor("0");
                   nodo1 = tmp;
      nodo1 = per(nodo1);
      jj_consume_token(Permisof);
hijo.addHijo(nodo1);
      hijo = datousu(hijo);
{if ("" != null) return hijo;}
      break;
      }
    default:
      jj_la1[11] = jj_gen;
{if ("" != null) return hijo;}
    }
    throw new Error("Missing return statement in function");
  }

  final public Nodo noper(Nodo hijo2) throws ParseException {Token t1;
    Nodo nodo1;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case Dbi:{
      jj_consume_token(Dbi);
      t1 = jj_consume_token(Id);
Nodo tmp = new Nodo(t1.image);
                    tmp.setNumNodo(graxml.contador++);
                    tmp.setValor("0");
                    nodo1 = tmp;
      jj_consume_token(Dbf);
      nodo1 = connoper(nodo1);
hijo2.addHijo(nodo1);
                                    {if ("" != null) return hijo2;}
      break;
      }
    default:
      jj_la1[12] = jj_gen;
{if ("" != null) return hijo2;}
    }
    throw new Error("Missing return statement in function");
  }

  final public Nodo connoper(Nodo hijo3) throws ParseException {Token t1;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case Obusui:{
      jj_consume_token(Obusui);
      t1 = jj_consume_token(Id);
Nodo tmp = new Nodo(t1.image);
                       tmp.setNumNodo(graxml.contador++);
                       tmp.setValor("0");
                       hijo3.addHijo(tmp);
      jj_consume_token(Obusuf);
      hijo3 = connoper(hijo3);
{if ("" != null) return hijo3;}
      break;
      }
    default:
      jj_la1[13] = jj_gen;
{if ("" != null) return hijo3;}
    }
    throw new Error("Missing return statement in function");
  }

  final public Nodo per(Nodo hijo2) throws ParseException {Token t1;
    Nodo nodo1;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case Dbi:{
      jj_consume_token(Dbi);
      t1 = jj_consume_token(Id);
Nodo tmp = new Nodo(t1.image);
                     tmp.setNumNodo(graxml.contador++);
                     tmp.setValor("0");
                     nodo1 = tmp;
      jj_consume_token(Dbf);
      nodo1 = conper(nodo1);
hijo2.addHijo(nodo1);
                                {if ("" != null) return hijo2;}
      break;
      }
    default:
      jj_la1[14] = jj_gen;
{if ("" != null) return hijo2;}
    }
    throw new Error("Missing return statement in function");
  }

  final public Nodo conper(Nodo hijo3) throws ParseException {Token t1;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case Obusui:{
      jj_consume_token(Obusui);
      t1 = jj_consume_token(Id);
Nodo tmp = new Nodo(t1.image);
                       tmp.setNumNodo(graxml.contador++);
                       tmp.setValor("0");
                       hijo3.addHijo(tmp);
      jj_consume_token(Obusuf);
      hijo3 = per(hijo3);
{if ("" != null) return hijo3;}
      break;
      }
    case Todos:{
      jj_consume_token(Todos);
Nodo tmp = new Nodo("Todos");
                 tmp.setNumNodo(graxml.contador++);
                 tmp.setValor("0");
                 hijo3.addHijo(tmp);
                 {if ("" != null) return hijo3;}
      break;
      }
    default:
      jj_la1[15] = jj_gen;
{if ("" != null) return hijo3;}
    }
    throw new Error("Missing return statement in function");
  }

  /** Generated Token Manager. */
  public graxmlTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private int jj_gen;
  final private int[] jj_la1 = new int[16];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static private int[] jj_la1_2;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
      jj_la1_init_2();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x4100,0x40,0x1500000,0x54000000,0x0,0x40000,0x0,0x0,0x0,0x400,0x0,0x400,0x40,0x0,0x40,0x0,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x150000,0x0,0x0,0x115,0x0,0x0,0x100,0x0,0x100,0x0,0x400000,0x15000000,0x0,0x40000000,0x0,0x40000000,};
   }
   private static void jj_la1_init_2() {
      jj_la1_2 = new int[] {0x0,0x0,0x0,0x0,0xf6,0x0,0x2000,0x11d00,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x1,};
   }

  /** Constructor with InputStream. */
  public graxml(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public graxml(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new graxmlTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 16; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 16; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public graxml(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new graxmlTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 16; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 16; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public graxml(graxmlTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 16; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(graxmlTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 16; i++) jj_la1[i] = -1;
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk_f() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[81];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 16; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
          if ((jj_la1_2[i] & (1<<j)) != 0) {
            la1tokens[64+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 81; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

}
