/* Generated By:JavaCC: Do not edit this line. graxmlConstants.java */
package gramatica_xml;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface graxmlConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int Dbi = 6;
  /** RegularExpression Id. */
  int Dbf = 7;
  /** RegularExpression Id. */
  int Nombrei = 8;
  /** RegularExpression Id. */
  int Nombref = 9;
  /** RegularExpression Id. */
  int Pathi = 10;
  /** RegularExpression Id. */
  int Pathf = 11;
  /** RegularExpression Id. */
  int Registroi = 12;
  /** RegularExpression Id. */
  int Registrof = 13;
  /** RegularExpression Id. */
  int Rowsi = 14;
  /** RegularExpression Id. */
  int Rowsf = 15;
  /** RegularExpression Id. */
  int Rowi = 16;
  /** RegularExpression Id. */
  int Rowf = 17;
  /** RegularExpression Id. */
  int Objecti = 18;
  /** RegularExpression Id. */
  int Objectf = 19;
  /** RegularExpression Id. */
  int Tablai = 20;
  /** RegularExpression Id. */
  int Tablaf = 21;
  /** RegularExpression Id. */
  int Procedurei = 22;
  /** RegularExpression Id. */
  int Proceduref = 23;
  /** RegularExpression Id. */
  int Texti = 24;
  /** RegularExpression Id. */
  int Textf = 25;
  /** RegularExpression Id. */
  int Inti = 26;
  /** RegularExpression Id. */
  int Intf = 27;
  /** RegularExpression Id. */
  int Doublei = 28;
  /** RegularExpression Id. */
  int Doublef = 29;
  /** RegularExpression Id. */
  int Booli = 30;
  /** RegularExpression Id. */
  int Boolf = 31;
  /** RegularExpression Id. */
  int Datei = 32;
  /** RegularExpression Id. */
  int Datef = 33;
  /** RegularExpression Id. */
  int Dateti = 34;
  /** RegularExpression Id. */
  int Datetf = 35;
  /** RegularExpression Id. */
  int Attri = 36;
  /** RegularExpression Id. */
  int Attrf = 37;
  /** RegularExpression Id. */
  int Obji = 38;
  /** RegularExpression Id. */
  int Objf = 39;
  /** RegularExpression Id. */
  int Srci = 40;
  /** RegularExpression Id. */
  int Srcf = 41;
  /** RegularExpression Id. */
  int Paramsi = 42;
  /** RegularExpression Id. */
  int Paramsf = 43;
  /** RegularExpression Id. */
  int Proci = 44;
  /** RegularExpression Id. */
  int Procf = 45;
  /** RegularExpression Id. */
  int Artablai = 46;
  /** RegularExpression Id. */
  int Artablaf = 47;
  /** RegularExpression Id. */
  int Arobji = 48;
  /** RegularExpression Id. */
  int Arobjf = 49;
  /** RegularExpression Id. */
  int Arusui = 50;
  /** RegularExpression Id. */
  int Arusuf = 51;
  /** RegularExpression Id. */
  int Usui = 52;
  /** RegularExpression Id. */
  int Usuf = 53;
  /** RegularExpression Id. */
  int Contai = 54;
  /** RegularExpression Id. */
  int Contaf = 55;
  /** RegularExpression Id. */
  int Noperi = 56;
  /** RegularExpression Id. */
  int Noperf = 57;
  /** RegularExpression Id. */
  int Permisoi = 58;
  /** RegularExpression Id. */
  int Permisof = 59;
  /** RegularExpression Id. */
  int Obusui = 60;
  /** RegularExpression Id. */
  int Obusuf = 61;
  /** RegularExpression Id. */
  int Todos = 62;
  /** RegularExpression Id. */
  int Pk = 63;
  /** RegularExpression Id. */
  int Fki = 64;
  /** RegularExpression Id. */
  int Fkf = 65;
  /** RegularExpression Id. */
  int Nulo = 66;
  /** RegularExpression Id. */
  int Auto = 67;
  /** RegularExpression Id. */
  int Unico = 68;
  /** RegularExpression Id. */
  int Nnulo = 69;
  /** RegularExpression Id. */
  int Id = 70;
  /** RegularExpression Id. */
  int Ruta = 71;
  /** RegularExpression Id. */
  int Num = 72;
  /** RegularExpression Id. */
  int Date = 73;
  /** RegularExpression Id. */
  int Datetime = 74;
  /** RegularExpression Id. */
  int Ai = 75;
  /** RegularExpression Id. */
  int Af = 76;
  /** RegularExpression Id. */
  int D = 77;
  /** RegularExpression Id. */
  int Texto = 78;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"\\t\"",
    "\"<DB>\"",
    "\"</DB>\"",
    "\"<nombre>\"",
    "\"</nombre>\"",
    "\"<path>\"",
    "\"</path>\"",
    "\"<registro>\"",
    "\"</registro>\"",
    "\"<rows>\"",
    "\"</rows>\"",
    "\"<row>\"",
    "\"</row>\"",
    "\"<object>\"",
    "\"</object>\"",
    "\"<tabla>\"",
    "\"</tabla>\"",
    "\"<procedure>\"",
    "\"</procedure>\"",
    "\"<text>\"",
    "\"</text>\"",
    "\"<int>\"",
    "\"</int>\"",
    "\"<Doublei>\"",
    "\"</Doublef>\"",
    "\"<bool>\"",
    "\"</bool>\"",
    "\"<date>\"",
    "\"</date>\"",
    "\"<datetime>\"",
    "\"</datetime>\"",
    "\"<attr>\"",
    "\"</attr>\"",
    "\"<obj>\"",
    "\"</obj>\"",
    "\"<src>\"",
    "\"</src>\"",
    "\"<params>\"",
    "\"</params>\"",
    "\"<proc>\"",
    "\"</proc>\"",
    "\"<artabla>\"",
    "\"</artabla>\"",
    "\"<arobj>\"",
    "\"</arobj>\"",
    "\"<arusu>\"",
    "\"</arusu>\"",
    "\"<usu>\"",
    "\"</usu>\"",
    "\"<conta>\"",
    "\"</conta>\"",
    "\"<noper>\"",
    "\"</noper>\"",
    "\"<permiso>\"",
    "\"</permiso>\"",
    "\"<Obusu>\"",
    "\"</Obusu>\"",
    "\"<todos>\"",
    "\"<pk>\"",
    "\"<fk>\"",
    "\"</fk>\"",
    "\"<nulo>\"",
    "\"<auto>\"",
    "\"<unico>\"",
    "\"<nnulo>\"",
    "<Id>",
    "<Ruta>",
    "<Num>",
    "<Date>",
    "<Datetime>",
    "\"<\"",
    "\">\"",
    "\"/\"",
    "<Texto>",
  };

}
