/* Generated By:JavaCC: Do not edit this line. grapqConstants.java */
package gramatica_paquete;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface grapqConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int Validar = 7;
  /** RegularExpression Id. */
  int Login = 8;
  /** RegularExpression Id. */
  int Paquete = 9;
  /** RegularExpression Id. */
  int Fin = 10;
  /** RegularExpression Id. */
  int Error = 11;
  /** RegularExpression Id. */
  int Tipo = 12;
  /** RegularExpression Id. */
  int Msg = 13;
  /** RegularExpression Id. */
  int Datos = 14;
  /** RegularExpression Id. */
  int Lexico = 15;
  /** RegularExpression Id. */
  int Archivo = 16;
  /** RegularExpression Id. */
  int Col = 17;
  /** RegularExpression Id. */
  int Fila = 18;
  /** RegularExpression Id. */
  int Instruccion = 19;
  /** RegularExpression Id. */
  int Reporte = 20;
  /** RegularExpression Id. */
  int Usql = 21;
  /** RegularExpression Id. */
  int Comando = 22;
  /** RegularExpression Id. */
  int Lenguaje = 23;
  /** RegularExpression Id. */
  int Usuario = 24;
  /** RegularExpression Id. */
  int Pass = 25;
  /** RegularExpression Id. */
  int Num = 26;
  /** RegularExpression Id. */
  int Id = 27;
  /** RegularExpression Id. */
  int Pai = 28;
  /** RegularExpression Id. */
  int Paf = 29;
  /** RegularExpression Id. */
  int Pt = 30;
  /** RegularExpression Id. */
  int Cm = 31;
  /** RegularExpression Id. */
  int Lli = 32;
  /** RegularExpression Id. */
  int Llf = 33;
  /** RegularExpression Id. */
  int Flecha = 34;
  /** RegularExpression Id. */
  int Igual = 35;
  /** RegularExpression Id. */
  int Pp = 36;
  /** RegularExpression Id. */
  int Cii = 37;
  /** RegularExpression Id. */
  int Cif = 38;
  /** RegularExpression Id. */
  int punto = 39;
  /** RegularExpression Id. */
  int Coi = 40;
  /** RegularExpression Id. */
  int Cof = 41;
  /** RegularExpression Id. */
  int Comi = 42;
  /** RegularExpression Id. */
  int Comilla = 43;
  /** RegularExpression Id. */
  int And = 44;
  /** RegularExpression Id. */
  int Sql = 45;
  /** RegularExpression Id. */
  int Texto = 46;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"\\t\"",
    "\"\\u201c\"",
    "\"\\\"validar\\\"\"",
    "\"\\\"login\\\"\"",
    "\"\\\"paquete\\\"\"",
    "\"\\\"fin\\\"\"",
    "\"\\\"error\\\"\"",
    "\"\\\"tipo\\\"\"",
    "\"\\\"msg\\\"\"",
    "\"\\\"datos\\\"\"",
    "\"\\\"lexico\\\"\"",
    "\"\\\"archivo\\\"\"",
    "\"\\\"col\\\"\"",
    "\"\\\"Fila\\\"\"",
    "\"\\\"instruccion\\\"\"",
    "\"\\\"reporte\\\"\"",
    "\"\\\"usql\\\"\"",
    "\"\\\"Comando\\\"\"",
    "\"\\\"Lenguaje\\\"\"",
    "\"seleccionar * de usuarios donde usuario =\"",
    "\"password\"",
    "<Num>",
    "<Id>",
    "\"(\"",
    "\")\"",
    "\";\"",
    "\",\"",
    "\"{\"",
    "\"}\"",
    "\"=>\"",
    "\"=\"",
    "\":\"",
    "\"<<\"",
    "\">>\"",
    "\".\"",
    "\"[\"",
    "\"]\"",
    "\"\\\'\"",
    "\"\\\"\"",
    "\"&&\"",
    "<Sql>",
    "<Texto>",
  };

}
