/* Generated By:JavaCC: Do not edit this line. grausuConstants.java */
package gramatica_usu;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface grausuConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int Crear = 6;
  /** RegularExpression Id. */
  int Nombrei = 7;
  /** RegularExpression Id. */
  int Nombref = 8;
  /** RegularExpression Id. */
  int BaseD = 9;
  /** RegularExpression Id. */
  int NombreT = 10;
  /** RegularExpression Id. */
  int Objeto = 11;
  /** RegularExpression Id. */
  int Procedimiento = 12;
  /** RegularExpression Id. */
  int Funcion = 13;
  /** RegularExpression Id. */
  int Tabla = 14;
  /** RegularExpression Id. */
  int Text = 15;
  /** RegularExpression Id. */
  int Integer = 16;
  /** RegularExpression Id. */
  int Double = 17;
  /** RegularExpression Id. */
  int Bool = 18;
  /** RegularExpression Id. */
  int TDate = 19;
  /** RegularExpression Id. */
  int TDateT = 20;
  /** RegularExpression Id. */
  int NoNulo = 21;
  /** RegularExpression Id. */
  int Nulo = 22;
  /** RegularExpression Id. */
  int AutoI = 23;
  /** RegularExpression Id. */
  int LlaveP = 24;
  /** RegularExpression Id. */
  int LlaveF = 25;
  /** RegularExpression Id. */
  int Unico = 26;
  /** RegularExpression Id. */
  int Id = 27;
  /** RegularExpression Id. */
  int Aid = 28;
  /** RegularExpression Id. */
  int Ruta = 29;
  /** RegularExpression Id. */
  int Num = 30;
  /** RegularExpression Id. */
  int Date = 31;
  /** RegularExpression Id. */
  int Datetime = 32;
  /** RegularExpression Id. */
  int Pai = 33;
  /** RegularExpression Id. */
  int Paf = 34;
  /** RegularExpression Id. */
  int Pt = 35;
  /** RegularExpression Id. */
  int Cm = 36;
  /** RegularExpression Id. */
  int Lli = 37;
  /** RegularExpression Id. */
  int Llf = 38;
  /** RegularExpression Id. */
  int Texto = 39;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"\\t\"",
    "\"crear\"",
    "\"<nombre>\"",
    "\"</nombre>\"",
    "\"base_datos\"",
    "\"nombre_tabla\"",
    "\"Objeto\"",
    "\"Procedimiento\"",
    "\"funcion\"",
    "\"tabla\"",
    "\"text\"",
    "\"integer\"",
    "\"double\"",
    "\"bool\"",
    "\"date\"",
    "\"datetime\"",
    "\"no nulo\"",
    "\"nulo\"",
    "\"autoincrementable\"",
    "\"llave_primaria\"",
    "\"llave_foranea\"",
    "\"unico\"",
    "<Id>",
    "<Aid>",
    "<Ruta>",
    "<Num>",
    "<Date>",
    "<Datetime>",
    "\"(\"",
    "\")\"",
    "\";\"",
    "\",\"",
    "\"{\"",
    "\"}\"",
    "<Texto>",
  };

}
