/* grausuTokenManager.java */
/* Generated By:JavaCC: Do not edit this line. grausuTokenManager.java */
package gramatica_usu;
import java.io.*;
import java.util.*;

/** Token Manager. */
@SuppressWarnings("unused")public class grausuTokenManager implements grausuConstants {
     Token tok;

  /** Debug output. */
  public  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private final int jjStopStringLiteralDfa_0(int pos, long active0){
   switch (pos)
   {
      case 0:
         if ((active0 & 0x7fffe00L) != 0L)
         {
            jjmatchedKind = 27;
            return 1;
         }
         if ((active0 & 0x40L) != 0L)
         {
            jjmatchedKind = 27;
            return 5;
         }
         return -1;
      case 1:
         if ((active0 & 0x7fffe40L) != 0L)
         {
            jjmatchedKind = 27;
            jjmatchedPos = 1;
            return 1;
         }
         return -1;
      case 2:
         if ((active0 & 0x200000L) != 0L)
         {
            if (jjmatchedPos < 1)
            {
               jjmatchedKind = 27;
               jjmatchedPos = 1;
            }
            return -1;
         }
         if ((active0 & 0x7dffe40L) != 0L)
         {
            jjmatchedKind = 27;
            jjmatchedPos = 2;
            return 1;
         }
         return -1;
      case 3:
         if ((active0 & 0x200000L) != 0L)
         {
            if (jjmatchedPos < 1)
            {
               jjmatchedKind = 27;
               jjmatchedPos = 1;
            }
            return -1;
         }
         if ((active0 & 0x5c8000L) != 0L)
            return 1;
         if ((active0 & 0x7837e40L) != 0L)
         {
            if (jjmatchedPos != 3)
            {
               jjmatchedKind = 27;
               jjmatchedPos = 3;
            }
            return 1;
         }
         return -1;
      case 4:
         if ((active0 & 0x200000L) != 0L)
         {
            if (jjmatchedPos < 1)
            {
               jjmatchedKind = 27;
               jjmatchedPos = 1;
            }
            return -1;
         }
         if ((active0 & 0x4004040L) != 0L)
            return 1;
         if ((active0 & 0x3933e00L) != 0L)
         {
            jjmatchedKind = 27;
            jjmatchedPos = 4;
            return 1;
         }
         return -1;
      case 5:
         if ((active0 & 0x200000L) != 0L)
         {
            if (jjmatchedPos < 1)
            {
               jjmatchedKind = 27;
               jjmatchedPos = 1;
            }
            return -1;
         }
         if ((active0 & 0x20800L) != 0L)
            return 1;
         if ((active0 & 0x3913600L) != 0L)
         {
            jjmatchedKind = 27;
            jjmatchedPos = 5;
            return 1;
         }
         return -1;
      case 6:
         if ((active0 & 0x200000L) != 0L)
         {
            if (jjmatchedPos < 1)
            {
               jjmatchedKind = 27;
               jjmatchedPos = 1;
            }
            return -1;
         }
         if ((active0 & 0x12000L) != 0L)
            return 1;
         if ((active0 & 0x3901600L) != 0L)
         {
            jjmatchedKind = 27;
            jjmatchedPos = 6;
            return 1;
         }
         return -1;
      case 7:
         if ((active0 & 0x100000L) != 0L)
            return 1;
         if ((active0 & 0x3801600L) != 0L)
         {
            jjmatchedKind = 27;
            jjmatchedPos = 7;
            return 1;
         }
         return -1;
      case 8:
         if ((active0 & 0x3801600L) != 0L)
         {
            jjmatchedKind = 27;
            jjmatchedPos = 8;
            return 1;
         }
         return -1;
      case 9:
         if ((active0 & 0x3801400L) != 0L)
         {
            jjmatchedKind = 27;
            jjmatchedPos = 9;
            return 1;
         }
         if ((active0 & 0x200L) != 0L)
            return 1;
         return -1;
      case 10:
         if ((active0 & 0x3801400L) != 0L)
         {
            jjmatchedKind = 27;
            jjmatchedPos = 10;
            return 1;
         }
         return -1;
      case 11:
         if ((active0 & 0x400L) != 0L)
            return 1;
         if ((active0 & 0x3801000L) != 0L)
         {
            jjmatchedKind = 27;
            jjmatchedPos = 11;
            return 1;
         }
         return -1;
      case 12:
         if ((active0 & 0x2001000L) != 0L)
            return 1;
         if ((active0 & 0x1800000L) != 0L)
         {
            jjmatchedKind = 27;
            jjmatchedPos = 12;
            return 1;
         }
         return -1;
      case 13:
         if ((active0 & 0x800000L) != 0L)
         {
            jjmatchedKind = 27;
            jjmatchedPos = 13;
            return 1;
         }
         if ((active0 & 0x1000000L) != 0L)
            return 1;
         return -1;
      case 14:
         if ((active0 & 0x800000L) != 0L)
         {
            jjmatchedKind = 27;
            jjmatchedPos = 14;
            return 1;
         }
         return -1;
      case 15:
         if ((active0 & 0x800000L) != 0L)
         {
            jjmatchedKind = 27;
            jjmatchedPos = 15;
            return 1;
         }
         return -1;
      default :
         return -1;
   }
}
private final int jjStartNfa_0(int pos, long active0){
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
}
private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private int jjMoveStringLiteralDfa0_0(){
   switch(curChar)
   {
      case 13:
         jjmatchedKind = 3;
         return jjMoveStringLiteralDfa1_0(0x10L);
      case 40:
         return jjStopAtPos(0, 33);
      case 41:
         return jjStopAtPos(0, 34);
      case 44:
         return jjStopAtPos(0, 36);
      case 59:
         return jjStopAtPos(0, 35);
      case 60:
         return jjMoveStringLiteralDfa1_0(0x180L);
      case 65:
      case 97:
         return jjMoveStringLiteralDfa1_0(0x800000L);
      case 66:
      case 98:
         return jjMoveStringLiteralDfa1_0(0x40200L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa1_0(0x40L);
      case 68:
      case 100:
         return jjMoveStringLiteralDfa1_0(0x1a0000L);
      case 70:
      case 102:
         return jjMoveStringLiteralDfa1_0(0x2000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa1_0(0x10000L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa1_0(0x3000000L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa1_0(0x600400L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa1_0(0x800L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa1_0(0x1000L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa1_0(0xc000L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa1_0(0x4000000L);
      case 123:
         return jjStopAtPos(0, 37);
      case 125:
         return jjStopAtPos(0, 38);
      default :
         return jjMoveNfa_0(0, 0);
   }
}
private int jjMoveStringLiteralDfa1_0(long active0){
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0);
      return 1;
   }
   switch(curChar)
   {
      case 10:
         if ((active0 & 0x10L) != 0L)
            return jjStopAtPos(1, 4);
         break;
      case 47:
         return jjMoveStringLiteralDfa2_0(active0, 0x100L);
      case 65:
      case 97:
         return jjMoveStringLiteralDfa2_0(active0, 0x184200L);
      case 66:
      case 98:
         return jjMoveStringLiteralDfa2_0(active0, 0x800L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa2_0(active0, 0x8000L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa2_0(active0, 0x3000000L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa2_0(active0, 0x4010080L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa2_0(active0, 0x260400L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa2_0(active0, 0x1040L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa2_0(active0, 0xc02000L);
      default :
         break;
   }
   return jjStartNfa_0(0, active0);
}
private int jjMoveStringLiteralDfa2_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(0, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0);
      return 2;
   }
   switch(curChar)
   {
      case 32:
         return jjMoveStringLiteralDfa3_0(active0, 0x200000L);
      case 65:
      case 97:
         return jjMoveStringLiteralDfa3_0(active0, 0x3000000L);
      case 66:
      case 98:
         return jjMoveStringLiteralDfa3_0(active0, 0x4000L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa3_0(active0, 0x40L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa3_0(active0, 0x4000000L);
      case 74:
      case 106:
         return jjMoveStringLiteralDfa3_0(active0, 0x800L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa3_0(active0, 0x400000L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa3_0(active0, 0x400L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa3_0(active0, 0x2100L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa3_0(active0, 0x41080L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa3_0(active0, 0x200L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa3_0(active0, 0x990000L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa3_0(active0, 0x20000L);
      case 88:
      case 120:
         return jjMoveStringLiteralDfa3_0(active0, 0x8000L);
      default :
         break;
   }
   return jjStartNfa_0(1, active0);
}
private int jjMoveStringLiteralDfa3_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(1, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0);
      return 3;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa4_0(active0, 0x40L);
      case 66:
      case 98:
         return jjMoveStringLiteralDfa4_0(active0, 0x20400L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa4_0(active0, 0x4003000L);
      case 69:
      case 101:
         if ((active0 & 0x80000L) != 0L)
         {
            jjmatchedKind = 19;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_0(active0, 0x110a00L);
      case 76:
      case 108:
         if ((active0 & 0x40000L) != 0L)
            return jjStartNfaWithStates_0(3, 18, 1);
         return jjMoveStringLiteralDfa4_0(active0, 0x4000L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa4_0(active0, 0x80L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa4_0(active0, 0x200000L);
      case 79:
      case 111:
         if ((active0 & 0x400000L) != 0L)
            return jjStartNfaWithStates_0(3, 22, 1);
         return jjMoveStringLiteralDfa4_0(active0, 0x800100L);
      case 84:
      case 116:
         if ((active0 & 0x8000L) != 0L)
            return jjStartNfaWithStates_0(3, 15, 1);
         break;
      case 86:
      case 118:
         return jjMoveStringLiteralDfa4_0(active0, 0x3000000L);
      default :
         break;
   }
   return jjStartNfa_0(2, active0);
}
private int jjMoveStringLiteralDfa4_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(2, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0);
      return 4;
   }
   switch(curChar)
   {
      case 95:
         return jjMoveStringLiteralDfa5_0(active0, 0x200L);
      case 65:
      case 97:
         if ((active0 & 0x4000L) != 0L)
            return jjStartNfaWithStates_0(4, 14, 1);
         break;
      case 66:
      case 98:
         return jjMoveStringLiteralDfa5_0(active0, 0x80L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa5_0(active0, 0x3001000L);
      case 71:
      case 103:
         return jjMoveStringLiteralDfa5_0(active0, 0x10000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa5_0(active0, 0x802000L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa5_0(active0, 0x20000L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa5_0(active0, 0x100L);
      case 79:
      case 111:
         if ((active0 & 0x4000000L) != 0L)
            return jjStartNfaWithStates_0(4, 26, 1);
         break;
      case 82:
      case 114:
         if ((active0 & 0x40L) != 0L)
            return jjStartNfaWithStates_0(4, 6, 1);
         return jjMoveStringLiteralDfa5_0(active0, 0x400L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa5_0(active0, 0x100800L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa5_0(active0, 0x200000L);
      default :
         break;
   }
   return jjStartNfa_0(3, active0);
}
private int jjMoveStringLiteralDfa5_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(3, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0);
      return 5;
   }
   switch(curChar)
   {
      case 95:
         return jjMoveStringLiteralDfa6_0(active0, 0x3000000L);
      case 66:
      case 98:
         return jjMoveStringLiteralDfa6_0(active0, 0x100L);
      case 68:
      case 100:
         return jjMoveStringLiteralDfa6_0(active0, 0x1200L);
      case 69:
      case 101:
         if ((active0 & 0x20000L) != 0L)
            return jjStartNfaWithStates_0(5, 17, 1);
         return jjMoveStringLiteralDfa6_0(active0, 0x10400L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa6_0(active0, 0x100000L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa6_0(active0, 0x200000L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa6_0(active0, 0x800000L);
      case 79:
      case 111:
         if ((active0 & 0x800L) != 0L)
            return jjStartNfaWithStates_0(5, 11, 1);
         return jjMoveStringLiteralDfa6_0(active0, 0x2000L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa6_0(active0, 0x80L);
      default :
         break;
   }
   return jjStartNfa_0(4, active0);
}
private int jjMoveStringLiteralDfa6_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(4, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0);
      return 6;
   }
   switch(curChar)
   {
      case 95:
         return jjMoveStringLiteralDfa7_0(active0, 0x400L);
      case 65:
      case 97:
         return jjMoveStringLiteralDfa7_0(active0, 0x200L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa7_0(active0, 0x800000L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa7_0(active0, 0x80L);
      case 70:
      case 102:
         return jjMoveStringLiteralDfa7_0(active0, 0x2000000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa7_0(active0, 0x1000L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa7_0(active0, 0x100000L);
      case 78:
      case 110:
         if ((active0 & 0x2000L) != 0L)
            return jjStartNfaWithStates_0(6, 13, 1);
         break;
      case 79:
      case 111:
         if ((active0 & 0x200000L) != 0L)
            return jjStopAtPos(6, 21);
         break;
      case 80:
      case 112:
         return jjMoveStringLiteralDfa7_0(active0, 0x1000000L);
      case 82:
      case 114:
         if ((active0 & 0x10000L) != 0L)
            return jjStartNfaWithStates_0(6, 16, 1);
         return jjMoveStringLiteralDfa7_0(active0, 0x100L);
      default :
         break;
   }
   return jjStartNfa_0(5, active0);
}
private int jjMoveStringLiteralDfa7_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(5, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0);
      return 7;
   }
   switch(curChar)
   {
      case 62:
         if ((active0 & 0x80L) != 0L)
            return jjStopAtPos(7, 7);
         break;
      case 69:
      case 101:
         if ((active0 & 0x100000L) != 0L)
            return jjStartNfaWithStates_0(7, 20, 1);
         return jjMoveStringLiteralDfa8_0(active0, 0x100L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa8_0(active0, 0x1000L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa8_0(active0, 0x2000000L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa8_0(active0, 0x1800000L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa8_0(active0, 0x600L);
      default :
         break;
   }
   return jjStartNfa_0(6, active0);
}
private int jjMoveStringLiteralDfa8_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(6, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0);
      return 8;
   }
   switch(curChar)
   {
      case 62:
         if ((active0 & 0x100L) != 0L)
            return jjStopAtPos(8, 8);
         break;
      case 65:
      case 97:
         return jjMoveStringLiteralDfa9_0(active0, 0x400L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa9_0(active0, 0x800000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa9_0(active0, 0x1001000L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa9_0(active0, 0x200L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa9_0(active0, 0x2000000L);
      default :
         break;
   }
   return jjStartNfa_0(7, active0);
}
private int jjMoveStringLiteralDfa9_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(7, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(8, active0);
      return 9;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa10_0(active0, 0x2000000L);
      case 66:
      case 98:
         return jjMoveStringLiteralDfa10_0(active0, 0x400L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa10_0(active0, 0x1000L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa10_0(active0, 0x1800000L);
      case 83:
      case 115:
         if ((active0 & 0x200L) != 0L)
            return jjStartNfaWithStates_0(9, 9, 1);
         break;
      default :
         break;
   }
   return jjStartNfa_0(8, active0);
}
private int jjMoveStringLiteralDfa10_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(8, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(9, active0);
      return 10;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa11_0(active0, 0x1000000L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa11_0(active0, 0x800000L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa11_0(active0, 0x400L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa11_0(active0, 0x2001000L);
      default :
         break;
   }
   return jjStartNfa_0(9, active0);
}
private int jjMoveStringLiteralDfa11_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(9, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(10, active0);
      return 11;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         if ((active0 & 0x400L) != 0L)
            return jjStartNfaWithStates_0(11, 10, 1);
         break;
      case 69:
      case 101:
         return jjMoveStringLiteralDfa12_0(active0, 0x2000000L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa12_0(active0, 0x800000L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa12_0(active0, 0x1000000L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa12_0(active0, 0x1000L);
      default :
         break;
   }
   return jjStartNfa_0(10, active0);
}
private int jjMoveStringLiteralDfa12_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(10, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(11, active0);
      return 12;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         if ((active0 & 0x2000000L) != 0L)
            return jjStartNfaWithStates_0(12, 25, 1);
         break;
      case 73:
      case 105:
         return jjMoveStringLiteralDfa13_0(active0, 0x1000000L);
      case 79:
      case 111:
         if ((active0 & 0x1000L) != 0L)
            return jjStartNfaWithStates_0(12, 12, 1);
         break;
      case 84:
      case 116:
         return jjMoveStringLiteralDfa13_0(active0, 0x800000L);
      default :
         break;
   }
   return jjStartNfa_0(11, active0);
}
private int jjMoveStringLiteralDfa13_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(11, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(12, active0);
      return 13;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         if ((active0 & 0x1000000L) != 0L)
            return jjStartNfaWithStates_0(13, 24, 1);
         return jjMoveStringLiteralDfa14_0(active0, 0x800000L);
      default :
         break;
   }
   return jjStartNfa_0(12, active0);
}
private int jjMoveStringLiteralDfa14_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(12, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(13, active0);
      return 14;
   }
   switch(curChar)
   {
      case 66:
      case 98:
         return jjMoveStringLiteralDfa15_0(active0, 0x800000L);
      default :
         break;
   }
   return jjStartNfa_0(13, active0);
}
private int jjMoveStringLiteralDfa15_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(13, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(14, active0);
      return 15;
   }
   switch(curChar)
   {
      case 76:
      case 108:
         return jjMoveStringLiteralDfa16_0(active0, 0x800000L);
      default :
         break;
   }
   return jjStartNfa_0(14, active0);
}
private int jjMoveStringLiteralDfa16_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(14, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(15, active0);
      return 16;
   }
   switch(curChar)
   {
      case 69:
      case 101:
         if ((active0 & 0x800000L) != 0L)
            return jjStartNfaWithStates_0(16, 23, 1);
         break;
      default :
         break;
   }
   return jjStartNfa_0(15, active0);
}
private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
static final long[] jjbitVec0 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 63;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 5:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 27)
                        kind = 27;
                     { jjCheckNAdd(1); }
                  }
                  else if (curChar == 58)
                     { jjCheckNAddTwoStates(6, 13); }
                  break;
               case 0:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 30)
                        kind = 30;
                     { jjCheckNAddTwoStates(15, 16); }
                  }
                  else if (curChar == 34)
                     { jjCheckNAddStates(0, 2); }
                  if ((0x3fe000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(29, 40); }
                  else if (curChar == 48)
                     { jjAddStates(3, 4); }
                  if ((0xe000000000000L & l) != 0L)
                     { jjAddStates(5, 6); }
                  break;
               case 1:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 27)
                     kind = 27;
                  { jjCheckNAdd(1); }
                  break;
               case 4:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 28)
                     kind = 28;
                  jjstateSet[jjnewStateCnt++] = 4;
                  break;
               case 6:
                  if (curChar == 47)
                     jjstateSet[jjnewStateCnt++] = 7;
                  break;
               case 8:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddStates(7, 9); }
                  break;
               case 13:
                  if (curChar == 46)
                     jjstateSet[jjnewStateCnt++] = 12;
                  break;
               case 15:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 30)
                     kind = 30;
                  { jjCheckNAddTwoStates(15, 16); }
                  break;
               case 16:
                  if (curChar == 46)
                     { jjCheckNAdd(17); }
                  break;
               case 17:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 30)
                     kind = 30;
                  { jjCheckNAdd(17); }
                  break;
               case 18:
                  if (curChar == 34)
                     { jjCheckNAddStates(0, 2); }
                  break;
               case 19:
                  if ((0xfffffffbffffdbffL & l) != 0L)
                     { jjCheckNAddStates(0, 2); }
                  break;
               case 21:
                  if ((0x8400000000L & l) != 0L)
                     { jjCheckNAddStates(0, 2); }
                  break;
               case 22:
                  if (curChar == 34 && kind > 39)
                     kind = 39;
                  break;
               case 23:
                  if ((0xff000000000000L & l) != 0L)
                     { jjCheckNAddStates(10, 13); }
                  break;
               case 24:
                  if ((0xff000000000000L & l) != 0L)
                     { jjCheckNAddStates(0, 2); }
                  break;
               case 25:
                  if ((0xf000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 26;
                  break;
               case 26:
                  if ((0xff000000000000L & l) != 0L)
                     { jjCheckNAdd(24); }
                  break;
               case 27:
                  if (curChar == 48)
                     { jjAddStates(3, 4); }
                  break;
               case 28:
                  if ((0x3fe000000000000L & l) != 0L)
                     { jjCheckNAdd(29); }
                  break;
               case 29:
                  if (curChar == 45)
                     { jjCheckNAddStates(14, 16); }
                  break;
               case 30:
                  if (curChar == 48)
                     { jjCheckNAdd(31); }
                  break;
               case 31:
                  if ((0x3fe000000000000L & l) != 0L)
                     { jjCheckNAdd(32); }
                  break;
               case 32:
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 33;
                  break;
               case 33:
                  if ((0x3fe000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 34;
                  break;
               case 34:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 35;
                  break;
               case 35:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 36;
                  break;
               case 36:
                  if ((0x3ff000000000000L & l) != 0L && kind > 31)
                     kind = 31;
                  break;
               case 37:
                  if (curChar == 49)
                     jjstateSet[jjnewStateCnt++] = 38;
                  break;
               case 38:
                  if ((0x7000000000000L & l) != 0L)
                     { jjCheckNAdd(32); }
                  break;
               case 39:
                  if ((0x3fe000000000000L & l) != 0L)
                     { jjCheckNAdd(40); }
                  break;
               case 40:
                  if (curChar == 45)
                     { jjCheckNAddStates(17, 19); }
                  break;
               case 41:
                  if (curChar == 48)
                     { jjCheckNAdd(42); }
                  break;
               case 42:
                  if ((0x3fe000000000000L & l) != 0L)
                     { jjCheckNAdd(43); }
                  break;
               case 43:
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 44;
                  break;
               case 44:
                  if ((0x3fe000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 45;
                  break;
               case 45:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 46;
                  break;
               case 46:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 47;
                  break;
               case 47:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 48;
                  break;
               case 48:
                  if (curChar == 32)
                     jjstateSet[jjnewStateCnt++] = 49;
                  break;
               case 49:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 50;
                  break;
               case 50:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 51;
                  break;
               case 51:
                  if (curChar == 58)
                     jjstateSet[jjnewStateCnt++] = 52;
                  break;
               case 52:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 53;
                  break;
               case 53:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 54;
                  break;
               case 54:
                  if (curChar == 58)
                     jjstateSet[jjnewStateCnt++] = 55;
                  break;
               case 55:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 56;
                  break;
               case 56:
                  if ((0x3ff000000000000L & l) != 0L && kind > 32)
                     kind = 32;
                  break;
               case 57:
                  if (curChar == 49)
                     jjstateSet[jjnewStateCnt++] = 58;
                  break;
               case 58:
                  if ((0x7000000000000L & l) != 0L)
                     { jjCheckNAdd(43); }
                  break;
               case 59:
                  if ((0x3fe000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(29, 40); }
                  break;
               case 60:
                  if ((0xe000000000000L & l) != 0L)
                     { jjAddStates(5, 6); }
                  break;
               case 61:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAdd(29); }
                  break;
               case 62:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAdd(40); }
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 5:
               case 1:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 27)
                     kind = 27;
                  { jjCheckNAdd(1); }
                  break;
               case 0:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 27)
                        kind = 27;
                     { jjCheckNAdd(1); }
                  }
                  else if (curChar == 64)
                     jjstateSet[jjnewStateCnt++] = 3;
                  if ((0x800000008L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 5;
                  break;
               case 2:
                  if (curChar == 64)
                     jjstateSet[jjnewStateCnt++] = 3;
                  break;
               case 3:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 28)
                     kind = 28;
                  { jjCheckNAdd(4); }
                  break;
               case 4:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 28)
                     kind = 28;
                  { jjCheckNAdd(4); }
                  break;
               case 7:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     { jjCheckNAddStates(7, 9); }
                  break;
               case 8:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     { jjCheckNAddStates(7, 9); }
                  break;
               case 9:
                  if ((0x800000008L & l) != 0L && kind > 29)
                     kind = 29;
                  break;
               case 10:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 9;
                  break;
               case 11:
                  if ((0x8000000080000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 10;
                  break;
               case 12:
                  if ((0x20000000200000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 11;
                  break;
               case 14:
                  if ((0x800000008L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 5;
                  break;
               case 19:
                  if ((0xffffffffefffffffL & l) != 0L)
                     { jjCheckNAddStates(0, 2); }
                  break;
               case 20:
                  if (curChar == 92)
                     { jjAddStates(20, 22); }
                  break;
               case 21:
                  if ((0x14404410144044L & l) != 0L)
                     { jjCheckNAddStates(0, 2); }
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 19:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     { jjAddStates(0, 2); }
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 63 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   19, 20, 22, 28, 39, 61, 62, 6, 8, 13, 19, 20, 24, 22, 30, 31, 
   37, 41, 42, 57, 21, 23, 25, 
};

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, "\50", "\51", "\73", "\54", "\173", "\175", null, };
protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

/** Get the next Token. */
public Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(java.io.IOException e)
   {
      jjmatchedKind = 0;
      jjmatchedPos = -1;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   try { input_stream.backup(0);
      while (curChar <= 32 && (0x100000600L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

    /** Constructor. */
    public grausuTokenManager(SimpleCharStream stream){

      if (SimpleCharStream.staticFlag)
            throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");

    input_stream = stream;
  }

  /** Constructor. */
  public grausuTokenManager (SimpleCharStream stream, int lexState){
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Reinitialise parser. */
  public void ReInit(SimpleCharStream stream)
  {
    jjmatchedPos = jjnewStateCnt = 0;
    curLexState = defaultLexState;
    input_stream = stream;
    ReInitRounds();
  }

  private void ReInitRounds()
  {
    int i;
    jjround = 0x80000001;
    for (i = 63; i-- > 0;)
      jjrounds[i] = 0x80000000;
  }

  /** Reinitialise parser. */
  public void ReInit(SimpleCharStream stream, int lexState)
  {
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Switch to specified lex state. */
  public void SwitchTo(int lexState)
  {
    if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
    else
      curLexState = lexState;
  }

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};
static final long[] jjtoToken = {
   0xffffffffc1L, 
};
static final long[] jjtoSkip = {
   0x3eL, 
};
    protected SimpleCharStream  input_stream;

    private final int[] jjrounds = new int[63];
    private final int[] jjstateSet = new int[2 * 63];

    
    protected char curChar;
}
