/* grausu.java */
/* Generated By:JavaCC: Do not edit this line. grausu.java */
package gramatica_usu;
import java.io.*;
import java.util.*;

public class grausu implements grausuConstants {
    public static void main( String[] args )throws ParseException
        {
                try
                {
                        grausu analizador = new grausu( System.in ) ;
                        analizador.inicio();
                        System.out.println("analisis correcto");
                }
                catch(ParseException e)
                {
                        System.out.println(e.getMessage());
                        System.out.println("Analizador: Se han encontrado errores en el analisis.");
                }
        }

  final public void inicio() throws ParseException {
    instrucciones();
    jj_consume_token(0);
  }

  final public void instrucciones() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case Crear:{
      crear();
      break;
      }
    case Usar:{
      usar();
      break;
      }
    case Alterar:{
      jj_consume_token(Alterar);
      alterar();
      break;
      }
    case Eliminar:{
      jj_consume_token(Eliminar);
      eliminar();
      break;
      }
    case Insertar:{
      jj_consume_token(Insertar);
      insertar();
      break;
      }
    case BackupU:{
      jj_consume_token(BackupU);
      backupu();
      break;
      }
    case BackupC:{
      jj_consume_token(BackupC);
      backupc();
      break;
      }
    case RestaU:{
      jj_consume_token(RestaU);
      restau();
      break;
      }
    case RestaC:{
      jj_consume_token(RestaC);
      restac();
      break;
      }
    case Actualizar:{
      jj_consume_token(Actualizar);
      jj_consume_token(Tabla);
      actualizar();
      break;
      }
    default:
      jj_la1[0] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

//*********************************************************************************Instruccion CREAR
  final public 
void crear() throws ParseException {
    jj_consume_token(Crear);
    tipocrear();
  }

  final public void tipocrear() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case BaseD:{
      jj_consume_token(BaseD);
      crearbase();
      break;
      }
    case Tabla:{
      jj_consume_token(Tabla);
      creartabla();
      break;
      }
    case Objeto:{
      jj_consume_token(Objeto);
      crearobjeto();
      break;
      }
    case Procedimiento:{
      jj_consume_token(Procedimiento);
      crearproce();
      break;
      }
    case Funcion:{
      jj_consume_token(Funcion);
      crearfuncion();
      break;
      }
    case Usuario:{
      jj_consume_token(Usuario);
      crearusuario();
      break;
      }
    default:
      jj_la1[1] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void crearbase() throws ParseException {
    jj_consume_token(Id);
    pt();
  }

  final public void creartabla() throws ParseException {
    jj_consume_token(Id);
    jj_consume_token(Pai);
    creaparametros();
    jj_consume_token(Paf);
    pt();
  }

  final public void crearobjeto() throws ParseException {
    jj_consume_token(Id);
    jj_consume_token(Pai);
    creaparametros();
    jj_consume_token(Paf);
    pt();
  }

  final public void creaparametros() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case Text:
    case Integer:
    case Double:
    case Bool:
    case TDate:
    case TDateT:
    case Id:{
      tipodato();
      jj_consume_token(Id);
      complemento();
      break;
      }
    default:
      jj_la1[2] = jj_gen;
{if ("" != null) return;}
    }
  }

  final public void complemento() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case Nulo:{
      jj_consume_token(Nulo);
      complemento();
      break;
      }
    case NoNulo:{
      jj_consume_token(NoNulo);
      complemento();
      break;
      }
    case AutoI:{
      jj_consume_token(AutoI);
      complemento();
      break;
      }
    case LlaveP:{
      jj_consume_token(LlaveP);
      complemento();
      break;
      }
    case LlaveF:{
      jj_consume_token(LlaveF);
      jj_consume_token(Id);
      break;
      }
    case Cm:{
      jj_consume_token(Cm);
      creaparametros();
      break;
      }
    default:
      jj_la1[3] = jj_gen;
{if ("" != null) return;}
    }
  }

  final public void tipodato() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case Text:{
      jj_consume_token(Text);
      break;
      }
    case Integer:{
      jj_consume_token(Integer);
      break;
      }
    case Double:{
      jj_consume_token(Double);
      break;
      }
    case Bool:{
      jj_consume_token(Bool);
      break;
      }
    case TDate:{
      jj_consume_token(TDate);
      break;
      }
    case TDateT:{
      jj_consume_token(TDateT);
      break;
      }
    case Id:{
      jj_consume_token(Id);
      break;
      }
    default:
      jj_la1[4] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void crearproce() throws ParseException {
    jj_consume_token(Id);
    jj_consume_token(Pai);
    paraproce();
    jj_consume_token(Paf);
    jj_consume_token(Lli);
    llf();
  }

  final public void paraproce() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case Text:
    case Integer:
    case Double:
    case Bool:
    case TDate:
    case TDateT:
    case Id:{
      tipodato();
      jj_consume_token(Aid);
      cmproce();
      break;
      }
    default:
      jj_la1[5] = jj_gen;
{if ("" != null) return;}
    }
  }

  final public void cmproce() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case Cm:{
      jj_consume_token(Cm);
      paraproce();
      break;
      }
    default:
      jj_la1[6] = jj_gen;
{if ("" != null) return;}
    }
  }

  final public void crearfuncion() throws ParseException {
    jj_consume_token(Id);
    jj_consume_token(Pai);
    paraproce();
    jj_consume_token(Paf);
    jj_consume_token(Lli);
    llf();
  }

  final public void pt() throws ParseException {
    try {
      jj_consume_token(Pt);
    } catch (ParseException x) {
System.out.println(x.toString());
                Token t;
                do {
                        t = getNextToken();
        } while (t.kind != Pt);
    }
  }

  final public void llf() throws ParseException {
    try {
      jj_consume_token(Llf);
    } catch (ParseException x) {
System.out.println(x.toString());
                Token t;
                do {
                        t = getNextToken();
        } while (t.kind != Llf);
    }
  }

  final public void crearusuario() throws ParseException {
    jj_consume_token(Id);
    jj_consume_token(Colocar);
    jj_consume_token(Pass);
    jj_consume_token(Igual);
    jj_consume_token(Texto);
    pt();
  }

//**************************************************************************INSTRUCCION USAR
  final public 
void usar() throws ParseException {
    jj_consume_token(Usar);
    jj_consume_token(Id);
    pt();
  }

//****************************************************************************INSTRUCCION ALTERAR
  final public 
void alterar() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case Tabla:{
      jj_consume_token(Tabla);
      jj_consume_token(Id);
      tablaalt();
      break;
      }
    case Objeto:{
      jj_consume_token(Objeto);
      jj_consume_token(Id);
      objalt();
      break;
      }
    case Usuario:{
      jj_consume_token(Usuario);
      jj_consume_token(Id);
      usualt();
      break;
      }
    default:
      jj_la1[7] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void tablaalt() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case Agregar:{
      jj_consume_token(Agregar);
      jj_consume_token(Pai);
      tipodato();
      jj_consume_token(Id);
      compoalt();
      setablaalt();
      jj_consume_token(Paf);
      pt();
      break;
      }
    case Quitar:{
      jj_consume_token(Quitar);
      jj_consume_token(Id);
      quitarseg();
      pt();
      break;
      }
    default:
      jj_la1[8] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void quitarseg() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case Cm:{
      jj_consume_token(Cm);
      jj_consume_token(Id);
      quitarseg();
      break;
      }
    default:
      jj_la1[9] = jj_gen;
{if ("" != null) return;}
    }
  }

  final public void setablaalt() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case Cm:{
      jj_consume_token(Cm);
      tipodato();
      jj_consume_token(Id);
      compoalt();
      setablaalt();
      break;
      }
    default:
      jj_la1[10] = jj_gen;
{if ("" != null) return;}
    }
  }

  final public void compoalt() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case Nulo:{
      jj_consume_token(Nulo);
      compoalt();
      break;
      }
    case NoNulo:{
      jj_consume_token(NoNulo);
      compoalt();
      break;
      }
    case AutoI:{
      jj_consume_token(AutoI);
      compoalt();
      break;
      }
    case LlaveP:{
      jj_consume_token(LlaveP);
      compoalt();
      break;
      }
    case LlaveF:{
      jj_consume_token(LlaveF);
      jj_consume_token(Id);
      break;
      }
    default:
      jj_la1[11] = jj_gen;
{if ("" != null) return;}
    }
  }

  final public void objalt() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case Agregar:{
      jj_consume_token(Agregar);
      jj_consume_token(Pai);
      tipodato();
      jj_consume_token(Id);
      segobjalt();
      jj_consume_token(Paf);
      pt();
      break;
      }
    case Quitar:{
      jj_consume_token(Quitar);
      jj_consume_token(Id);
      quitarseg();
      pt();
      break;
      }
    default:
      jj_la1[12] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void segobjalt() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case Cm:{
      jj_consume_token(Cm);
      tipodato();
      jj_consume_token(Id);
      compoalt();
      segobjalt();
      break;
      }
    default:
      jj_la1[13] = jj_gen;
{if ("" != null) return;}
    }
  }

  final public void usualt() throws ParseException {
    jj_consume_token(Cambiar);
    jj_consume_token(Pass);
    jj_consume_token(Igual);
    jj_consume_token(Texto);
    pt();
  }

//*****************************************************************************Instruccion Eliminar
  final public 
void eliminar() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case Tabla:{
      jj_consume_token(Tabla);
      jj_consume_token(Id);
      pt();
      break;
      }
    case BaseD:{
      jj_consume_token(BaseD);
      jj_consume_token(Id);
      pt();
      break;
      }
    case Objeto:{
      jj_consume_token(Objeto);
      jj_consume_token(Id);
      pt();
      break;
      }
    case Usuario:{
      jj_consume_token(Usuario);
      jj_consume_token(Id);
      pt();
      break;
      }
    default:
      jj_la1[14] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

//*******************************************************************************Instruccion insertar
  final public 
void insertar() throws ParseException {
    jj_consume_token(En);
    jj_consume_token(Tabla);
    jj_consume_token(Id);
    jj_consume_token(Pai);
    tipo();
    listavalores();
    jj_consume_token(Paf);
    especial();
    pt();
  }

  final public void listavalores() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case Cm:{
      jj_consume_token(Cm);
      tipo();
      listavalores();
      break;
      }
    default:
      jj_la1[15] = jj_gen;
{if ("" != null) return;}
    }
  }

  final public void tipo() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case Id:{
      jj_consume_token(Id);
      break;
      }
    case Aid:{
      jj_consume_token(Aid);
      break;
      }
    case Num:{
      jj_consume_token(Num);
      break;
      }
    case Texto:{
      jj_consume_token(Texto);
      break;
      }
    case Date:{
      jj_consume_token(Date);
      break;
      }
    case Datetime:{
      jj_consume_token(Datetime);
      break;
      }
    default:
      jj_la1[16] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void especial() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case Valores:{
      jj_consume_token(Valores);
      jj_consume_token(Pai);
      tipo();
      listavalores();
      jj_consume_token(Paf);
      break;
      }
    default:
      jj_la1[17] = jj_gen;
{if ("" != null) return;}
    }
  }

//***********************************************************************BACKUP y Restaurar
  final public 
void backupu() throws ParseException {
    jj_consume_token(Id);
    jj_consume_token(Id);
    pt();
  }

  final public void backupc() throws ParseException {
    jj_consume_token(Id);
    jj_consume_token(Id);
    pt();
  }

  final public void restau() throws ParseException {
    jj_consume_token(RutaU);
    pt();
  }

  final public void restac() throws ParseException {
    jj_consume_token(RutaZ);
    pt();
  }

//************************************************************************** Instruccion ACTUALIZAR
  final public 
void actualizar() throws ParseException {
    s0();
  }

//************************************************************************ operaciones
  final public 
void s0() throws ParseException {
    s1();
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case Suma:
      case Resta:{
        ;
        break;
        }
      default:
        jj_la1[18] = jj_gen;
        break label_1;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case Suma:{
        jj_consume_token(Suma);
        break;
        }
      case Resta:{
        jj_consume_token(Resta);
        break;
        }
      default:
        jj_la1[19] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      s1();
    }
  }

  final public void s1() throws ParseException {
    s2();
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case Divi:
      case Mult:{
        ;
        break;
        }
      default:
        jj_la1[20] = jj_gen;
        break label_2;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case Divi:{
        jj_consume_token(Divi);
        break;
        }
      case Mult:{
        jj_consume_token(Mult);
        break;
        }
      default:
        jj_la1[21] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      s2();
    }
  }

  final public void s2() throws ParseException {
    s3();
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case Pote:{
        ;
        break;
        }
      default:
        jj_la1[22] = jj_gen;
        break label_3;
      }
      jj_consume_token(Pote);
      s3();
    }
  }

  final public void s3() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case Resta:{
      jj_consume_token(Resta);
      s4();
      break;
      }
    case Id:
    case Aid:
    case Num:
    case Date:
    case Datetime:
    case Not:
    case Pai:
    case Texto:{
      s4();
      break;
      }
    default:
      jj_la1[23] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void s4() throws ParseException {
    s5();
    label_4:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case Iguales:
      case Dife:
      case Menorq:
      case Mayorq:
      case Menori:
      case Mayori:{
        ;
        break;
        }
      default:
        jj_la1[24] = jj_gen;
        break label_4;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case Iguales:{
        jj_consume_token(Iguales);
        break;
        }
      case Dife:{
        jj_consume_token(Dife);
        break;
        }
      case Mayorq:{
        jj_consume_token(Mayorq);
        break;
        }
      case Menorq:{
        jj_consume_token(Menorq);
        break;
        }
      case Mayori:{
        jj_consume_token(Mayori);
        break;
        }
      case Menori:{
        jj_consume_token(Menori);
        break;
        }
      default:
        jj_la1[25] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      s5();
    }
  }

  final public void s5() throws ParseException {
    s6();
    label_5:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case And:{
        ;
        break;
        }
      default:
        jj_la1[26] = jj_gen;
        break label_5;
      }
      jj_consume_token(And);
      s6();
    }
  }

  final public void s6() throws ParseException {
    s7();
    label_6:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case Or:{
        ;
        break;
        }
      default:
        jj_la1[27] = jj_gen;
        break label_6;
      }
      jj_consume_token(Or);
      s7();
    }
  }

  final public void s7() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case Not:{
      jj_consume_token(Not);
      s8();
      break;
      }
    case Id:
    case Aid:
    case Num:
    case Date:
    case Datetime:
    case Pai:
    case Texto:{
      s8();
      break;
      }
    default:
      jj_la1[28] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void s8() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case Num:{
      jj_consume_token(Num);
      break;
      }
    case Texto:{
      jj_consume_token(Texto);
      break;
      }
    case Id:{
      jj_consume_token(Id);
      break;
      }
    case Aid:{
      jj_consume_token(Aid);
      break;
      }
    case Datetime:{
      jj_consume_token(Datetime);
      break;
      }
    case Date:{
      jj_consume_token(Date);
      break;
      }
    case Pai:{
      jj_consume_token(Pai);
      s0();
      jj_consume_token(Paf);
      break;
      }
    default:
      jj_la1[29] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  /** Generated Token Manager. */
  public grausuTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private int jj_gen;
  final private int[] jj_la1 = new int[30];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static private int[] jj_la1_2;
  static private int[] jj_la1_3;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
      jj_la1_init_2();
      jj_la1_init_3();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x3c1f800,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x0,0x1f40,0xfc000000,0x0,0xfc000000,0xfc000000,0x0,0x1900,0x18000,0x0,0x0,0x0,0x18000,0x0,0x1940,0x0,0x0,0x80000,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,};
   }
   private static void jj_la1_init_2() {
      jj_la1_2 = new int[] {0x0,0x0,0x40,0x8000001f,0x40,0x40,0x80000000,0x0,0x0,0x80000000,0x80000000,0x1f,0x0,0x80000000,0x0,0x80000000,0x38c0,0x0,0xc000,0xc000,0x30000,0x30000,0x40000,0x1800b8c0,0x1f80000,0x1f80000,0x2000000,0x4000000,0x180038c0,0x100038c0,};
   }
   private static void jj_la1_init_3() {
      jj_la1_3 = new int[] {0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x40,0x0,0x0,0x0,0x0,0x0,0x0,0x40,0x0,0x0,0x0,0x0,0x40,0x40,};
   }

  /** Constructor with InputStream. */
  public grausu(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public grausu(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new grausuTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 30; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 30; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public grausu(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new grausuTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 30; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 30; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public grausu(grausuTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 30; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(grausuTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 30; i++) jj_la1[i] = -1;
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk_f() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[103];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 30; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
          if ((jj_la1_2[i] & (1<<j)) != 0) {
            la1tokens[64+j] = true;
          }
          if ((jj_la1_3[i] & (1<<j)) != 0) {
            la1tokens[96+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 103; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

}
