/* Generated By:JavaCC: Do not edit this line. grausuConstants.java */
package gramatica_usu;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface grausuConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int Crear = 6;
  /** RegularExpression Id. */
  int Usar = 7;
  /** RegularExpression Id. */
  int Alterar = 8;
  /** RegularExpression Id. */
  int BaseD = 9;
  /** RegularExpression Id. */
  int NombreT = 10;
  /** RegularExpression Id. */
  int Objeto = 11;
  /** RegularExpression Id. */
  int Procedimiento = 12;
  /** RegularExpression Id. */
  int Funcion = 13;
  /** RegularExpression Id. */
  int Tabla = 14;
  /** RegularExpression Id. */
  int Usuario = 15;
  /** RegularExpression Id. */
  int Colocar = 16;
  /** RegularExpression Id. */
  int Pass = 17;
  /** RegularExpression Id. */
  int Agregar = 18;
  /** RegularExpression Id. */
  int Quitar = 19;
  /** RegularExpression Id. */
  int Cambiar = 20;
  /** RegularExpression Id. */
  int Text = 21;
  /** RegularExpression Id. */
  int Integer = 22;
  /** RegularExpression Id. */
  int Double = 23;
  /** RegularExpression Id. */
  int Bool = 24;
  /** RegularExpression Id. */
  int TDate = 25;
  /** RegularExpression Id. */
  int TDateT = 26;
  /** RegularExpression Id. */
  int Retorno = 27;
  /** RegularExpression Id. */
  int NoNulo = 28;
  /** RegularExpression Id. */
  int Nulo = 29;
  /** RegularExpression Id. */
  int AutoI = 30;
  /** RegularExpression Id. */
  int LlaveP = 31;
  /** RegularExpression Id. */
  int LlaveF = 32;
  /** RegularExpression Id. */
  int Unico = 33;
  /** RegularExpression Id. */
  int Id = 34;
  /** RegularExpression Id. */
  int Aid = 35;
  /** RegularExpression Id. */
  int Ruta = 36;
  /** RegularExpression Id. */
  int Num = 37;
  /** RegularExpression Id. */
  int Date = 38;
  /** RegularExpression Id. */
  int Datetime = 39;
  /** RegularExpression Id. */
  int Pai = 40;
  /** RegularExpression Id. */
  int Paf = 41;
  /** RegularExpression Id. */
  int Pt = 42;
  /** RegularExpression Id. */
  int Cm = 43;
  /** RegularExpression Id. */
  int Lli = 44;
  /** RegularExpression Id. */
  int Llf = 45;
  /** RegularExpression Id. */
  int Igual = 46;
  /** RegularExpression Id. */
  int Texto = 47;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"\\t\"",
    "\"crear\"",
    "\"usar\"",
    "\"Alterar\"",
    "\"base_datos\"",
    "\"nombre_tabla\"",
    "\"Objeto\"",
    "\"Procedimiento\"",
    "\"funcion\"",
    "\"tabla\"",
    "\"usuario\"",
    "\"colocar\"",
    "\"password\"",
    "\"Agregar\"",
    "\"quitar\"",
    "\"cambiar\"",
    "\"text\"",
    "\"integer\"",
    "\"double\"",
    "\"bool\"",
    "\"date\"",
    "\"datetime\"",
    "\"retorno\"",
    "\"no nulo\"",
    "\"nulo\"",
    "\"autoincrementable\"",
    "\"llave_primaria\"",
    "\"llave_foranea\"",
    "\"unico\"",
    "<Id>",
    "<Aid>",
    "<Ruta>",
    "<Num>",
    "<Date>",
    "<Datetime>",
    "\"(\"",
    "\")\"",
    "\";\"",
    "\",\"",
    "\"{\"",
    "\"}\"",
    "\"=\"",
    "<Texto>",
  };

}
