/* Generated By:JavaCC: Do not edit this line. letraConstants.java */
package gramatica_usu;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface letraConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int Entero = 5;
  /** RegularExpression Id. */
  int Caracter = 6;
  /** RegularExpression Id. */
  int Palabra = 7;
  /** RegularExpression Id. */
  int Pt = 8;
  /** RegularExpression Id. */
  int cm = 9;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"int\"",
    "\"char\"",
    "<Palabra>",
    "\";\"",
    "\",\"",
  };

}
